name: Bater Ponto

on:
  schedule:
    - cron: "0 11 * * 1-5" # 08:00 BRT → entrada
    - cron: "0 15 * * 1-5" # 12:00 BRT → saida_almoco
    - cron: "0 16 * * 1-5" # 13:00 BRT → volta_almoco
    - cron: "0 20 * * 1-5" # 17:00 BRT → saida_final
  workflow_dispatch:

jobs:
  ponto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instala Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instala o ChromeDriver compatível com o Chrome instalado
        run: |
          FULL_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          echo "Versão completa do Chrome: $FULL_VERSION"

          wget "https://storage.googleapis.com/chrome-for-testing-public/${FULL_VERSION}/linux64/chromedriver-linux64.zip" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Baixa jornada anterior (exceto na entrada)
        if: env.ETAPA_PONTO != 'entrada'
        uses: actions/download-artifact@v4
        with:
          name: jornada

      - name: Executa o script de ponto
        run: python main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
          PORTAL_URL: ${{ secrets.PORTAL_URL }}
          ETAPA_PONTO: ${{ github.event.schedule == '0 11 * * 1-5' && 'entrada' || github.event.schedule == '0 15 * * 1-5' && 'saida_almoco' || github.event.schedule == '0 16 * * 1-5' && 'volta_almoco' || 'saida_final' }}

      - name: Salva jornada após sorteio
        if: env.ETAPA_PONTO == 'entrada'
        uses: actions/upload-artifact@v4
        with:
          name: jornada-${{ github.run_id }}
          path: jornada.json
