name: Bater Ponto

on:
  schedule:
    - cron: "0 11 * * 1-5" # 08:00 BRT (ajuste se quiser)
    - cron: "0 15 * * 1-5" # 12:00 BRT
    - cron: "0 16 * * 1-5" # 13:00 BRT
    - cron: "0 20 * * 1-5" # 17:00 BRT
  workflow_dispatch: # Permite rodar manualmente

jobs:
  ponto:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instala Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instala o ChromeDriver compatível
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "Chrome version: $CHROME_VERSION"
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/${CHROME_VERSION}/linux64/chromedriver-linux64.zip"
          wget "$DRIVER_URL" -O chromedriver.zip
          unzip chromedriver.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Executa o script de ponto
        run: python main.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_DEST: ${{ secrets.EMAIL_DEST }}
          LOGIN_USER: ${{ secrets.LOGIN_USER }}
          LOGIN_PASS: ${{ secrets.LOGIN_PASS }}
          PORTAL_URL: ${{ secrets.PORTAL_URL }}
